### ISSUE TITLE
Issues using a db with migration

### ISSUE THREAD

**Issue by Crystal1462** [neozhu/RazorPageCleanArchitecture#100]
Short story,  everything works UseInMemoryDatabase is true.  Set that to false is when complications seem to come into existence.
First in the readme, Need to change the WebUI dir path.

dotnet ef migrations add "SampleMigration" --project src/Infrastructure --startup-project src/SmartAdmin.WebUI --output-dir Persistence/Migrations

Once this was done, I was able to update-database perfectly fine however when starting the project I get this exception on Host.Start()

MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Migrations.Operations.Builders.OperationBuilder`1<Microsoft.EntityFrameworkCore.Migrations.Operations.CreateIndexOperation> Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder.CreateIndex(System.String, System.String, System.String, System.String, Boolean, System.String)'.

This exception was originally thrown at this call stack:
Microsoft.EntityFrameworkCore.Migrations.Migration.BuildOperations(System.Action<Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder>)
   Microsoft.EntityFrameworkCore.Migrations.Migration.UpOperations.get()
   Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Microsoft.EntityFrameworkCore.Migrations.Migration, Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerationOptions)
   Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GetMigrationCommandLists.AnonymousMethod__2()
   Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(string)
   Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade)
   WorkflowCore.Persistence.EntityFramework.Services.EntityFrameworkPersistenceProvider.EnsureStoreExists()
   WorkflowCore.Services.WorkflowHost.StartAsync(System.Threading.CancellationToken)

I am using SQLExpress and Version 17.4.4

Thanks for any help you can provide

**Comment by neozhu** [comment]
<img width="1879" alt="image" src="https://user-images.githubusercontent.com/1549611/220353649-54f99b77-eb1b-48e5-8f4a-77ae1bf9178b.png">
set smartadmin.webui as startup project
open package manager console select default project: infrastructure
run > update-database or add-migration

**Comment by Crystal1462** [comment]
await userManager.CreateAsync(administrator, "Password123!");
Causes this:
Microsoft.Data.SqlClient.SqlException: 'Invalid column name 'IsLive'.'

This is where I attempted to create the new migration with this.
dotnet ef migrations add "SampleMigration" --project src/Infrastructure --startup-project src/SmartAdmin.WebUI --output-dir Persistence/Migrations

This gets you past that issue and on to the issue above.

**Comment by Crystal1462** [comment]
Found the issue...
Because of the issue with IsLive I had to handle the creation and migration myself which caused an error on this:
services.AddWorkflow(x => x.UseSqlServer(configuration.GetConnectionString("DefaultConnection"), true, true));
changed to:
services.AddWorkflow(x => x.UseSqlServer(configuration.GetConnectionString("DefaultConnection"), false, false));

Works fine now.

**Comment by Crystal1462** [comment]
Not sure why there is a difference in migration but in theory, I think all would have to happen is update the migration and should be fine with the current code.  Not tested it though.
