### ISSUE TITLE
Where is the OCR source code corresponding to the website http://razor.i247365.net? Can it be deployed locally?

### ISSUE THREAD

**Issue by dizhenx** [neozhu/RazorPageCleanArchitecture#101]
Where is the OCR source code corresponding to the website http://razor.i247365.net? Can it be deployed locally?

**Comment by neozhu** [comment]
sure

**Comment by dizhenx** [comment]
> sure

After executing "Navigate to src/WebUI/ClientApp and run npm start to launch the front end (Angular)," when I log in to the browser interface, the page appears in its original state. It doesn't have the OCR interface functionality displayed at razor.i247365.net. How can I load the OCR interface?

**Comment by neozhu** [comment]
You can refer to this open source project https://github.com/PaddlePaddle/PaddleOCR. It provides a Docker image, which you can use to run a Docker container and then it's ready to use.
