### ISSUE TITLE
Datatables

### ISSUE THREAD

**Issue by urmatgit** [neozhu/RazorPageCleanArchitecture#11]
Hello! 
How do I show the Datagrid in Modal dialogs? 
thanks

**Comment by neozhu** [comment]
about datagrid API please reference http://www.jeasyui.com/documentation/index.php, 
you can try this way listen shown event invoke datagrid.resize() 
```
$('#myModal').on('shown.bs.modal', function () {
   $('dg').resize();
})

**Comment by urmatgit** [comment]
![IMG_20210908_130409_188](https://user-images.githubusercontent.com/5357178/132489973-a250ac77-a3aa-472f-8795-7e22c44e3db6.jpg)
When open in modal page, datagrid is empty

**Comment by neozhu** [comment]
![image](https://user-images.githubusercontent.com/1549611/132504829-4fe2ee52-b07a-4a2d-9e67-7ba8299a7c9f.png)
![image](https://user-images.githubusercontent.com/1549611/132504940-fe06195c-0431-484d-8bf9-cbd4109369d1.png)
