### ISSUE TITLE
Not sending the Application DLL in Blazor WASM

### ISSUE THREAD

**Issue by garkpit** [neozhu/RazorPageCleanArchitecture#2]
When using Blazor in WASM - I want to _not_ send any of my business logic (Application) to the client. (I don't want them to reverse engineer it). I want to send only the things it actually needs = the DTOs.

Please can you split out the DTOs to a separate Project - e.g. Application.Dto - and make sure only that goes down the wire to the client?

Open to other ideas!

Thanks!

**Comment by neozhu** [comment]
That makes a lot of sense split application project.
Lightweight simplicity is the original intention, Work with [code generation tools](https://github.com/neozhu/CleanArchitectureCodeGenerator), and keep your business code in a single project.

**Comment by neozhu** [comment]
Blazor WASM is client mode. EF core(dbcontext) not support WASM
