### ISSUE TITLE
Adding a UserProfile class

### ISSUE THREAD

**Issue by HybridSolutions** [neozhu/RazorPageCleanArchitecture#73]
Hi,

great work here! You upgraded to .net 6 in the right way. I'm going to ask you something since it's an issue I'm facing with this architecture. Hope you help me on this.

I need to extend IdentityUser but I don't want to extend it so that I end up having my custom UsersProfile properties mixed with those in AspNetUsers table. I want to have a table for user profiles. My approach to this would be to create a Userprofile class in Domain.Entities to receive additional user info and somehow connect it with the IdentityUser. My problem is how can I have this in sync but not having to deal with IdentityUser and UserProfile in an isolated way. How could I implement this so that I could Register, update and delete users and their profiles with a single class?

Any idea on how I could achieve this? There's no examples on this feature and with this architecture.
Trying to follow this article, but would be great to have another opinion on this issue.

[Battling ASP.NET Core Identity – You WILL Follow the Navigation Properties](https://esagegroup.com/battling-asp-net-core-identity-you-will-follow-the-navigation-properties/)

For now, I added the UserProfile navigation property into ApplicationUser. Running a migration will add a new table UsersProfile to the database and the UserProfileId foreign key to the AspNetUsers table.

This will force to insert into the AspNetUsers table, the Id of the User profile. Is this the right approach? Should I override  UserStore so that I can change how data is read and written?

```
public class ApplicationUser: IdentityUser<int>
    {
        public int UserProfileId { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
```

```
namespace eCM.Core.Domain
{
    public class UserProfile: AuditEntity
    {
        /// <summary>
        /// Id of this User.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Username used for login.
        /// </summary>
        public string Username { get; set; }

        /// <summary>
        /// Name shown in menus / dialogs etc.
        /// </summary>
        public string DisplayName { get; set; }

        [StringLength(50)]
        public string FirstName { get; set; }

        [StringLength(50)]
        public string LastName { get; set; }

        [NotMapped]
        public string FullName { get { 
                return $"{FirstName} {LastName}".Trim(); } 
        }

        /// <summary>
        /// User E-Mail address.
        /// </summary>
        public string Email { get; set; }

        [StringLength(50)]
        public string JobPosition { get; set; }

        /// <summary>
        /// Reference to a <see cref="File"/> containing the users photo.
        /// </summary>
        [StringLength(50)]
        public string Photo { get; set; }

        [DefaultValue(true)]
        public bool IsListed { get; set; } = true;

        [DefaultValue(false)]
        public bool IsDisabled { get; set; } = false;

        [DefaultValue(false)]
        public bool IsLocked { get; set; } = false;

        /// <summary>
        /// Timestamp of last login.
        /// </summary>
        public DateTime? LastLoginDate { get; set; }

        public DateTime? LastActivityDate { get; set; }

        /// <summary>
        /// Tracking information of IP used when the user last worked on this site. 
        /// </summary>
        public string LastIPAddress { get; set; }

        [StringLength(100)]
        public string LastSessionId { get; set; }

        [StringLength(256)]
        public string PrivateFolder { get; set; }

        public bool IsOnApproval { get; set; } = true;


        // IdentityUser properties not mapped in the User table

        [NotMapped]
        public string Password { get; set; }

        [NotMapped]
        public bool IsAuthenticated { get; set; }

        [NotMapped]
        public string Roles { get; set; }
    }
}
```

Thanks!

**Comment by neozhu** [comment]
I know what you mean，You can add DbSet<UserProfile> in applicationContext.cs, use applicationcontext class for data maintenance.
```js
public class UserProfileData
{
    public int  Id { get; set; }
    public string Health { get; set; }
    public string ApplicationUserId { get; set; }
    public virtual ApplicationUser ApplicationUser { get; set; }
}
```

Another simple approach that define all properties in applicationUser.cs class, it's ok.

**Comment by neozhu** [comment]
I know what you mean，You can add DbSet<UserProfile> in applicationContext.cs, use applicationcontext class for data maintenance.
```js
public class UserProfileData
{
    public int  Id { get; set; }
    public string Health { get; set; }
    public string ApplicationUserId { get; set; }
    public virtual ApplicationUser ApplicationUser { get; set; }
}
```

Another simple approach that defines all properties in applicationUser.cs class, it's ok.

The perfect solution is to rewrite UserStore<> add DbSet<UserProfileData>

**Comment by HybridSolutions** [comment]
> I know what you mean，You can add DbSet in applicationContext.cs, use applicationcontext class for data maintenance.
> 
> ```js
> public class UserProfileData
> {
>     public int  Id { get; set; }
>     public string Health { get; set; }
>     public string ApplicationUserId { get; set; }
>     public virtual ApplicationUser ApplicationUser { get; set; }
> }
> ```
> 
> Another simple approach that define all properties in applicationUser.cs class, it's ok.

This will force me to have Identity in Domain layer. I would like to avoid that since it breaks the Clean Architecture pattern.

**Comment by neozhu** [comment]
I have an idea why not use UserClaims for storage user profile information. So you don't have to change any code

**Comment by HybridSolutions** [comment]
> I have an idea why not use UserClaims for storage user profile information. So you don't have to change any code

That's an idea. The issue I'm seeing is being able to access claims as properties in the front-end. Know any article on working with claims like that? 

I have a couple but strangely they all store data in AspNetUsers table and then load that data into claims! Always wondered why they didn't store that info as claims in the first place.

**Comment by VAllens** [comment]
cooooooool...
