### ISSUE TITLE
Licence for the theme?

### ISSUE THREAD

**Issue by PeterKneale** [neozhu/RazorPageCleanArchitecture#85]
How does licensing work in terms of it having a paid for theme? Do you have permission to redistribute their code?
Ref: https://wrapbootstrap.com/theme/smartadmin-responsive-webapp-WB0573SK0/

**Comment by neozhu** [comment]
I don't know, the smartadmin theme was downloaded from the website: https://www.escripts.club/,  Legally speaking, this is illegal. I hope you can buy it and use it again
