### ISSUE TITLE
Page error if entering a invalid address.

### ISSUE THREAD

**Issue by linkxu1989** [neozhu/RazorPageCleanArchitecture#88]
**Describe the bug**
See logs in the screenshot.

**To Reproduce**
1. Go to "https://localhost:44375/pages"
2. Refresh the page.
3. See console logs.
4. Click "Product" page, data could not be loaded.

**Expected behavior**
Clean the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/17608441/158998054-520414e0-0f18-41ab-8023-d4bc1e78799b.png)

**Additional context**
No

**Comment by neozhu** [comment]
this is a bugger, I have fixed.

**Comment by linkxu1989** [comment]
Goes to a wrong repository, sorry.
