### ISSUE TITLE
Start new Project with RazorPage CleanArchitecture

### ISSUE THREAD

**Issue by baffourt** [neozhu/RazorPageCleanArchitecture#91]
Is it possible to a `new ca-sln -razor` and start with this razor page template?
If there's already a way, let me know how to start with the razor page clean architecture template.

**Comment by neozhu** [comment]
Sorry, I don't know how to create a template from the project, let me know if you do it

**Comment by baffourt** [comment]
Alright, I will look into how to create a template with this. How do you go about starting a project using this as a template?

**Comment by neozhu** [comment]
I will not be updating this project anymore; I am working on the Blazorserver project https://github.com/neozhu/CleanArchitectureWithBlazorServer
