### ISSUE TITLE
The PaddleOCR Invoice Recognition Docker Image

### ISSUE THREAD

**Issue by yoesak** [neozhu/RazorPageCleanArchitecture#94]
Hi, 

Do you provide the url for the docker image invoice recognition, since in your code, you just hit to the https://paddleocr.i247365.net/predict/ocr_system ?

Thanks
Yusak 
Indonesia

**Comment by neozhu** [comment]
hello,
I build a docker image for paddleocr api
https://github.com/neozhu/PaddleOCRFastAPI
